---
- name: restart prometheus
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
  become: true
  tags: prometheus

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
  become: true
  tags: prometheus

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: prometheus
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: prometheus
  become: true