groups:
- name: prometheus
  rules:
  - alert: PrometheusConfigurationReload
    expr: prometheus_config_last_reload_successful != 1
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus configuration reload (instance {{ $labels.hostname }})"
      description: "Prometheus configuration reload error"
  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might be crashed."
  - alert: PrometheusAllTargetsMissing
    expr: count by (job) (up) == 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus all targets missing (instance {{ $labels.hostname }})"
      description: "A Prometheus job does not have living target anymore."
  - alert: PrometheusTooManyRestarts
    expr: changes(process_start_time_seconds{job=~"prometheus|pushgateway|alertmanager"}[15m]) > 2
    for: 5m
    labels:
      severity: standard
    annotations:
      summary: "Prometheus too many restarts (instance {{ $labels.hostname }})"
      description: "Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping."
  - alert: PrometheusNotConnectedToAlertmanager
    expr: prometheus_notifications_alertmanagers_discovered < 1
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus not connected to alertmanager (instance {{ $labels.hostname }})"
      description: "Prometheus cannot connect the alertmanager"
  - alert: PrometheusRuleEvaluationFailures
    expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus rule evaluation failures (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts."
  - alert: PrometheusTemplateTextExpansionFailures
    expr: increase(prometheus_template_text_expansion_failures_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus template text expansion failures (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} template text expansion failures"
  - alert: PrometheusRuleEvaluationSlow
    expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
    for: 5m
    labels:
      severity: standard
    annotations:
      summary: "Prometheus rule evaluation slow (instance {{ $labels.hostname }})"
      description: "Prometheus rule evaluation took more time than the scheduled interval. I indicates a slower storage backend access or too complex query."
  - alert: PrometheusNotificationsBacklog
    expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
    for: 5m
    labels:
      severity: standard
    annotations:
      summary: "Prometheus notifications backlog (instance {{ $labels.hostname }})"
      description: "The Prometheus notification queue has not been empty for 10 minutes"
#  - alert: PrometheusTargetEmpty
#    expr: prometheus_sd_discovered_targets == 0
#    for: 5m
#    labels:
#      severity: error
#    annotations:
#      summary: "Prometheus target empty (instance {{ $labels.hostname }})"
#      description: "Prometheus has no target in service discovery"
  - alert: PrometheusAlertmanagerNotificationFailing
    expr: rate(alertmanager_notifications_failed_total[1m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus AlertManager notification failing (instance {{ $labels.hostname }})"
      description: "Alertmanager is failing sending notifications"
  - alert: PrometheusLargeScrape
    expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
    for: 5m
    labels:
      severity: standard
    annotations:
      summary: "Prometheus large scrape (instance {{ $labels.hostname }})"
      description: "Prometheus has many scrapes that exceed the sample limit"
  - alert: PrometheusTargetScrapeDuplicate
    expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
    for: 5m
    labels:
      severity: standard
    annotations:
      summary: "Prometheus target scrape duplicate (instance {{ $labels.hostname }})"
      description: "Prometheus has many samples rejected due to duplicate timestamps but different values"
  - alert: PrometheusTsdbCheckpointCreationFailures
    expr: increase(prometheus_tsdb_checkpoint_creations_failed_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB checkpoint creation failures (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} checkpoint creation failures"
  - alert: PrometheusTsdbCheckpointDeletionFailures
    expr: increase(prometheus_tsdb_checkpoint_deletions_failed_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB checkpoint deletion failures (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} checkpoint deletion failures"
  - alert: PrometheusTsdbCompactionsFailed
    expr: increase(prometheus_tsdb_compactions_failed_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB compactions failed (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} TSDB compactions failures"
  - alert: PrometheusTsdbHeadTruncationsFailed
    expr: increase(prometheus_tsdb_head_truncations_failed_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB head truncations failed (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} TSDB head truncation failures"
  - alert: PrometheusTsdbReloadFailures
    expr: increase(prometheus_tsdb_reloads_failures_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB reload failures (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} TSDB reload failures"
  - alert: PrometheusTsdbWalCorruptions
    expr: increase(prometheus_tsdb_wal_corruptions_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB WAL corruptions (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} TSDB WAL corruptions"
  - alert: PrometheusTsdbWalTruncationsFailed
    expr: increase(prometheus_tsdb_wal_truncations_failed_total[3m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Prometheus TSDB WAL truncations failed (instance {{ $labels.hostname }})"
      description: "Prometheus encountered {{ $value }} TSDB WAL truncation failures"
